### ISSUE TITLE
Throwing Weapons

### ISSUE THREAD

**Issue by itsTripp** [itsTripp/Platformer_Shooter#22]
Apply damage to the enemies when a weapon is thrown.

**Comment by AfterMath24** [comment]
Goal is to complete this by 2/14

**Comment by AfterMath24** [comment]
All we need to do is allow a weapon to be thrown at the press of a button then apply the damage component to it and ensure it has a collider2d. 

I will attempt to work  on this tonight.

**Comment by AfterMath24** [comment]
Created a new damage component VelocityDamage that factors in the velocity of the thrown object and allows for setting min and max velocities. If the object is moving slower than the min velocity the damage and knockback are 0 otherwise the damage and velocity is a percentage of the maxDamage and maxKnockback based on velocity / maxVelocity.
